### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by dv-script** [dv-script/portfolio#1]
- [ ] Create the Routes
- [ ] Create a Navmenu
- [ ] Build the Home Page
- [ ] Build the About Page
- [ ] Build the Projects Page
- [ ] Build the Contact Page
